Contribute to json language server with a custom language. (#198583)
* Contribute to json language server with a custom language.

* Add `snippets` to `"activationEvents"`

* Remove hardcoded `snippets` from `documentSettings`

* Fix wrong variable in `!isEqualSet()`

* Use `extensions.allAcrossExtensionHosts` instead of `extensions.all`

* enable `"enabledApiProposals"` for `extensions.allAcrossExtensionHosts`

* Fix error: `Property 'allAcrossExtensionHosts' does not exist on type 'typeof extensions'`

* Remove `snippets`